<?php
session_start();

require_once "../../backend/config/database.php";

$database = new Database();
$conn = $database->connect();

$search = "";

if (isset($_GET['search'])) {

    $search = trim($_GET['search']);

    $stmt = $conn->prepare("
        SELECT
            r.report_id,
            r.report_name,
            r.report_type,
            u.full_name,
            r.generated_date
        FROM reports r
        INNER JOIN users u
            ON r.generated_by = u.user_id
        WHERE
            r.report_name LIKE ?
            OR r.report_type LIKE ?
        ORDER BY r.generated_date DESC
    ");

    $keyword = "%".$search."%";

    $stmt->execute([$keyword, $keyword]);

} else {

    $stmt = $conn->query("
        SELECT
            r.report_id,
            r.report_name,
            r.report_type,
            u.full_name,
            r.generated_date
        FROM reports r
        INNER JOIN users u
            ON r.generated_by = u.user_id
        ORDER BY r.generated_date DESC
    ");

}
?>

<!DOCTYPE html>
<html>

<head>

    <title>Reports</title>

    <link rel="stylesheet" href="../assets/css/style.css">

</head>

<body>

<div class="topbar">
    Internship Management System
</div>

<div class="layout">

<div class="sidebar">

<h3>Admin Panel</h3>

<a href="dashboard.php">Dashboard</a>
<a href="users.php">Users</a>
<a href="students.php">Students</a>
<a href="companies.php">Companies</a>
<a href="internships.php">Internships</a>
<a href="applications.php">Applications</a>
<a href="reports.php" class="active">Reports</a>
<a href="../authentication/logout.php">Logout</a>

</div>

<div class="content">

<div class="card">

<h2>Reports</h2>

<form method="GET">

<input
type="text"
name="search"
placeholder="Search report..."
value="<?= htmlspecialchars($search); ?>">

<button class="btn">
Search
</button>

</form>

</div>

<div class="card">

<table>

<tr>

<th>ID</th>
<th>Report Name</th>
<th>Report Type</th>
<th>Generated By</th>
<th>Date</th>

</tr>

<?php while($row = $stmt->fetch(PDO::FETCH_ASSOC)): ?>

<tr>

<td><?= $row['report_id']; ?></td>

<td><?= htmlspecialchars($row['report_name']); ?></td>

<td><?= htmlspecialchars($row['report_type']); ?></td>

<td><?= htmlspecialchars($row['full_name']); ?></td>

<td><?= $row['generated_date']; ?></td>

</tr>

<?php endwhile; ?>

</table>

</div>

</div>

</div>

</body>

</html>