<?php
session_start();

require_once "../../backend/config/database.php";
require_once "../../backend/classes/Report.php";

if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'admin') {
    header("Location: ../authentication/login.php");
    exit();
}

$reportObj = new Report();
$reports = null;
$search = "";

// Generate report
if (isset($_POST['generate_report'])) {
    $report_type = $_POST['report_type'] ?? '';
    
    switch ($report_type) {
        case 'applications':
            $reportObj->generateApplicationsReport($_SESSION['user_id']);
            $_SESSION['message'] = "Applications report generated.";
            break;
        case 'internships':
            $reportObj->generateInternshipsReport($_SESSION['user_id']);
            $_SESSION['message'] = "Internships report generated.";
            break;
        case 'students':
            $reportObj->generateStudentsReport($_SESSION['user_id']);
            $_SESSION['message'] = "Students report generated.";
            break;
    }
    header("Location: reports.php");
    exit();
}

// Search reports
if (isset($_GET['search'])) {
    $search = trim($_GET['search']);
    $reports = $reportObj->searchReports($search);
} else {
    $reports = $reportObj->getAllReports();
}

// Delete report
if (isset($_GET['delete'])) {
    $report_id = $_GET['delete'];
    if ($reportObj->deleteReport($report_id)) {
        $_SESSION['message'] = "Report deleted.";
    }
    header("Location: reports.php");
    exit();
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>Reports</title>
    <link rel="stylesheet" href="../assets/css/style.css">
</head>
<body>

<div class="topbar">
    Internship Management System
</div>

<div class="layout">
    <div class="sidebar">
        <h3>Admin Panel</h3>
        <a href="dashboard.php">Dashboard</a>
        <a href="users.php">Users</a>
        <a href="students.php">Students</a>
        <a href="companies.php">Companies</a>
        <a href="internships.php">Internships</a>
        <a href="applications.php">Applications</a>
        <a href="reports.php" class="active">Reports</a>
        <a href="../authentication/logout.php">Logout</a>
    </div>

    <div class="content">
        <div class="card">
            <h2>Generate Reports</h2>
            <?php if (isset($_SESSION['message'])): ?>
                <p class="success-msg"><?php echo $_SESSION['message']; unset($_SESSION['message']); ?></p>
            <?php endif; ?>
            
            <form method="POST" style="margin-bottom: 20px;">
                <select name="report_type" required>
                    <option value="">Select Report Type</option>
                    <option value="applications">Applications Report</option>
                    <option value="internships">Internships Report</option>
                    <option value="students">Students Report</option>
                </select>
                <button type="submit" name="generate_report" class="btn">Generate</button>
            </form>
        </div>

        <div class="card">
            <h2>Reports</h2>
            <form method="GET" style="margin-bottom: 20px;">
                <input type="text" name="search" placeholder="Search report..." 
                       value="<?= htmlspecialchars($search) ?>">
                <button class="btn">Search</button>
            </form>
        </div>

        <div class="card">
            <table>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Report Name</th>
                    <th>Type</th>
                    <th>Generated By</th>
                    <th>Generated Date</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php while ($row = $reports->fetch(PDO::FETCH_ASSOC)): ?>
                    <tr>
                        <td><?= htmlspecialchars($row['report_id']) ?></td>
                        <td><?= htmlspecialchars($row['report_name']) ?></td>
                        <td><?= htmlspecialchars($row['report_type']) ?></td>
                        <td><?= htmlspecialchars($row['full_name']) ?></td>
                        <td><?= htmlspecialchars($row['generated_date']) ?></td>
                        <td>
                            <a href="reports.php?delete=<?php echo $row['report_id']; ?>" 
                               onclick="return confirm('Delete this report?');" 
                               class="btn btn-danger" style="padding:5px 10px;font-size:12px;">Delete</a>
                        </td>
                    </tr>
                <?php endwhile; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php include "../layouts/footer.php"; ?>
</body>
</html>
